version: 0.2

env:
  variables:
    TF_VERSION: "1.8.5"
  # S3 backend values (optional, if using remote backend)
  # TF_BUCKET: "terraform-state-bucket"
  # TF_KEY: "vpc/terraform.tfstate"
  # TF_REGION: "ap-south-1"

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init

  build:
    commands:
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning infrastructure changes..."
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan
      - echo "Terraform apply completed successfully!"

artifacts:
  files:
    - "**/*"
