version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform_1.9.5_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Checking files..."
      - ls -R
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - terraform fmt -check
      - terraform validate
      - terraform plan -input=false -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan
